export const GET_CLOTHS_DATA_REQUEST = "GET_CLOTHS_DATA_REQUEST";
export const GET_CLOTHS_DATA_SUCCESS = "GET_CLOTHS_DATA_SUCCESS";
export const GET_CLOTHS_DATA_FAILURE = "GET_CLOTHS_DATA_FAILURE";

export const GET_CARTKEY_REQUEST = "GET_CARTKEY_REQUEST";

export const GET_CARTKEY_SUCCESS = "GET_CARTKEY_SUCCESS";

export const GET_CARTKEY_FAILURE = "GET_CARTKEY_FAILURE";

export const GET_CARTDATA_REQUEST = "GET_CARTDATA_REQUEST";

export const GET_CARTDATA_SUCCESS = "GET_CARTDATA_SUCCESS"

export const GET_CARTDATA_FAILURE = "GET_CARTDATA_FAILURE";

export const GET_DATA_LENGTH = " GET_DATA_LENGTH"


